services:
  postgres:
    image: postgres:16-alpine
    container_name: article_app_pg
    environment:
      POSTGRES_DB: article_app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
